spring:
  h2:
    console:
      enabled: true #enable H2 console to access on browser (chrome, firefox, any others)
      path: /h2-console #path to access the H2 console
  datasource:
    url: jdbc:h2:mem:walletserviceassignmentdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: root
    password:
    platform: h2
  jpa:
    database-plataform: org.hibernate.dialect.H2Dialect